name: Scrape chicken prices

on:
  schedule:
    # 毎日 23:00 UTC = JST 08:00
    - cron: "0 23 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm install

      - name: Run scraper
        run: node scripts/scrape.js

      - name: Commit & Push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(data): update chicken prices (auto)"
          file_pattern: docs/data/*
